[package]
name = "netmap-min-sys"
version = "0.3.0"
edition = "2021"
authors = ["Meshack Bahati Ouma <bahatikylemeshack@gmail.com>"]
description = "Raw FFI bindings and helpers for Netmap"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kyle6012/netmap-rs.git"
keywords = ['networking', 'ffi', 'netmap']
categories = ["api-bindings"]

[build-dependencies]
bindgen = "0.71.1"
cc = "1"

[dependencies]
libc = "0.2"

[features]
default = []
disable-netmap-kernel = []

[package.metadata.docs.rs]
features = ["disable-netmap-kernel"]
